-- ============================================================================
-- ЗАДАНИЕ ФИНАЛ: Создать таблицу readers
-- ============================================================================
CREATE TABLE readers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE readers_books (
    reader_id BIGINT NOT NULL references readers(id),
    book_id BIGINT NOT NULL references books(id),
    PRIMARY KEY (reader_id, book_id)
);
INSERT INTO readers (email, name) VALUES
    ('you@example.com', 'Хороший Человек'),
    ('test@example.com', 'Другой Человек');
INSERT INTO readers_books(reader_id, book_id) VALUES
    (1, 1),
    (1, 3),
    (2, 1),
    (2, 2);