-- ============================================================================
-- ЗАДАНИЕ ФИНАЛ: Создать таблицу readers
-- ============================================================================

CREATE TABLE readers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE reader_books (
    reader_id BIGINT NOT NULL REFERENCES readers(id) ON DELETE CASCADE,
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    PRIMARY KEY (reader_id, book_id)
);

CREATE INDEX idx_reader_books_reader ON reader_books(reader_id);
CREATE INDEX idx_reader_books_book ON reader_books(book_id);

INSERT INTO readers (name, email) VALUES
    ('Иван', 'ivan@example.com'),
    ('Мария', 'maria@example.com');

-- Связи: читатель 1 — книги 1 и 5; читатель 2 — книгу 7 (по порядку INSERT в V2)
INSERT INTO reader_books (reader_id, book_id) VALUES
    (1, 1),
    (1, 5),
    (2, 7);
